dns_packages:
  - bind9

dns_zone: "example.local"
dns_master_ip: "10.10.10.11"
dns_records:
  - name: "@"
    type: "A"
    value: "10.10.10.11"
  - name: "ns1"
    type: "A"
    value: "10.10.10.11"
  - name: "www"
    type: "A"
    value: "10.10.10.11"