"""Detection-validation gate: prove each fixture still triggers its expected finding.

Reads scanner JSON already generated by the workflow, rather than invoking
Checkov/Trivy itself, so the test checks the exact output the pipeline gate
sees instead of a second, possibly-different invocation.
"""

import json
import os
from pathlib import Path

import pytest

from expectations import FIXTURES

FIXTURES_DIR = Path(__file__).parent / "fixtures"
CHECKOV_JSON = Path(os.environ.get("CHECKOV_JSON", "checkov_fixtures.json"))
TRIVY_JSON = Path(os.environ.get("TRIVY_JSON", "trivy_fixtures.json"))


def _load_checkov_ids():
    """filename -> set of failed check_ids, across every framework in the report."""
    data = json.loads(CHECKOV_JSON.read_text())
    if isinstance(data, dict):
        data = [data]
    found = {}
    for entry in data:
        for check in entry["results"]["failed_checks"]:
            filename = Path(check["file_path"]).name
            found.setdefault(filename, set()).add(check["check_id"])
    return found


def _load_trivy_ids():
    """filename -> set of RuleIDs."""
    data = json.loads(TRIVY_JSON.read_text())
    found = {}
    for result in data.get("Results", []):
        filename = Path(result["Target"]).name
        for secret in result.get("Secrets", []):
            found.setdefault(filename, set()).add(secret["RuleID"])
    return found


@pytest.fixture(scope="session")
def checkov_ids():
    return _load_checkov_ids()


@pytest.fixture(scope="session")
def trivy_ids():
    return _load_trivy_ids()


@pytest.mark.parametrize("fixture_name,expected", FIXTURES.items(), ids=list(FIXTURES.keys()))
def test_checkov_detects(fixture_name, expected, checkov_ids):
    expected_ids = set(expected["checkov"])
    if not expected_ids:
        pytest.skip(f"{fixture_name} has no Checkov coverage by design")
    missing = expected_ids - checkov_ids.get(fixture_name, set())
    assert not missing, f"{fixture_name}: Checkov stopped detecting {missing}"


@pytest.mark.parametrize("fixture_name,expected", FIXTURES.items(), ids=list(FIXTURES.keys()))
def test_trivy_detects(fixture_name, expected, trivy_ids):
    expected_ids = set(expected["trivy"])
    if not expected_ids:
        pytest.skip(f"{fixture_name} has no Trivy coverage by design")
    missing = expected_ids - trivy_ids.get(fixture_name, set())
    assert not missing, f"{fixture_name}: Trivy stopped detecting {missing}"


def test_every_fixture_has_expectations():
    """Meta-test: every .tf fixture on disk must be declared in expectations.py."""
    on_disk = {p.name for p in FIXTURES_DIR.glob("*.tf")}
    undeclared = on_disk - set(FIXTURES.keys())
    assert not undeclared, f"fixtures missing from expectations.py: {undeclared}"
