id: infra-plan
namespace: homelab.infra

tasks:
  - id: workdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Cyb3rCl0n3/homelab
        branch: main

      - id: terraform_plan
        type: io.kestra.plugin.terraform.cli.TerraformCLI
        containerImage: hashicorp/terraform:1.9
        beforeCommands:
          - cd proxmox/terraform && terraform init
        commands:
          - terraform plan -no-color 2>&1 | tee plan_output.txt
        outputFiles:
          - "terraform/plan_output.txt"
        env:
          TF_VAR_proxmox_api_token: "{{ secret('PROXMOX_API_TOKEN')}}"
          TF_VAR_proxmox_endpoint: "{{ secret('PROXMOX_ENDPOINT') }}"